<a href="https://colab.research.google.com/github/rerebebeccacca/20210624-deep-learning-class/blob/main/01_RNN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [ ]:
# Sample: 1(幾個資料)
# Sequence Length: 5（幾個序列）
# feature dimension: 8（幾個特徵值）

inputs = tf.random.normal([1, 5, 8])

# tf.keras.layers.LSTM

In [ ]:
output = layers.LSTM(units=3)(inputs)
# output = layers.LSTM(units=3, return_sequences=True)(inputs)
print(output.shape)

(1, 5, 3)


In [ ]:
whole_seq_output, final_hiden_state, final_cell_state = layers.LSTM(3, 
                                                                    return_sequences=True, 
                                                                    return_state=True)(inputs)

print('whole_seq_output: ', whole_seq_output.shape, whole_seq_output)
print('final_hiden_state (h): ', final_hiden_state.shape, final_hiden_state)
print('final_cell_state (c): ', final_cell_state.shape, final_cell_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.08274251  0.03847694 -0.08997072]
  [-0.18739657  0.03410421 -0.05226758]
  [-0.12741375 -0.1293194   0.15615012]
  [-0.29839787 -0.13747336  0.1279253 ]
  [-0.24881704 -0.22742642  0.30899817]]], shape=(1, 5, 3), dtype=float32)
final_hiden_state (h):  (1, 3) tf.Tensor([[-0.24881704 -0.22742642  0.30899817]], shape=(1, 3), dtype=float32)
final_cell_state (c):  (1, 3) tf.Tensor([[-0.5390483  -0.49398562  0.38973188]], shape=(1, 3), dtype=float32)


# tf.keras.layers.GRU

In [ ]:
output = layers.GRU(units=3)(inputs)
print(output.shape)

(1, 3)


In [ ]:
whole_sequence_output, final_state = layers.GRU(3, 
                                                return_sequences=True, 
                                                return_state=True)(inputs)

print('whole_seq_output: ', whole_sequence_output.shape, whole_sequence_output)
print('final_state (h): ', final_state.shape, final_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.5560607   0.28374246  0.25326866]
  [ 0.0085808   0.11775172 -0.08572333]
  [ 0.2007084   0.2633381   0.1924465 ]
  [ 0.02568759  0.14472397  0.39672026]
  [ 0.50060195 -0.08630495 -0.14830774]]], shape=(1, 5, 3), dtype=float32)
final_state (h):  (1, 3) tf.Tensor([[ 0.50060195 -0.08630495 -0.14830774]], shape=(1, 3), dtype=float32)


# tf.keras.layers.Bidirectional

In [ ]:
output = layers.Bidirectional(layers.LSTM(3))(inputs)
print(output.shape)

(1, 6)


In [ ]:
# merge_mode: Sum
output = layers.Bidirectional(layers.LSTM(3), 
                              merge_mode='sum')(inputs)
print(output.shape)

(1, 3)


In [ ]:
# return_sequences: True
output = layers.Bidirectional(layers.LSTM(10, return_sequences=True))(inputs)
print(output.shape)

(1, 5, 20)


In [ ]:
# return_sequences: True, 
output, forward_h, forward_c, backward_h, backward_c = layers.Bidirectional(layers.LSTM(2, return_sequences=True, return_state=True))(inputs)
print('output : ', output.shape, output)
print('forward_h : ', forward_h.shape, forward_h)
print('forward_c : ', forward_c.shape, forward_c)
print('backward_h : ', backward_h.shape, backward_h)
print('backward_c : ', backward_c.shape, backward_c)


output :  (1, 5, 4) tf.Tensor(
[[[-0.4258836  -0.41512123  0.17933066  0.25858796]
  [-0.13122877 -0.10636536 -0.00643803  0.3362214 ]
  [-0.2668728  -0.23809105 -0.06205915  0.03952498]
  [-0.2913185  -0.15018088 -0.10638423  0.03257701]
  [-0.13747233 -0.14221376 -0.03071847  0.12122328]]], shape=(1, 5, 4), dtype=float32)
forward_h :  (1, 2) tf.Tensor([[-0.13747233 -0.14221376]], shape=(1, 2), dtype=float32)
forward_c :  (1, 2) tf.Tensor([[-1.0977627  -0.19781554]], shape=(1, 2), dtype=float32)
backward_h :  (1, 2) tf.Tensor([[0.17933066 0.25858796]], shape=(1, 2), dtype=float32)
backward_c :  (1, 2) tf.Tensor([[0.4359826 0.6157264]], shape=(1, 2), dtype=float32)


## Many-to-one

In [ ]:
input = layers.Input(shape=(5, 8))
x = layers.LSTM(2)(input)
ouput = layers.Dense(10, activation='softmax')(x)
model = models.Model(input, ouput)
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 2)                 88        
_________________________________________________________________
dense_2 (Dense)              (None, 10)                30        
Total params: 118
Trainable params: 118
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# multi-layer
input = layers.Input(shape=(5, 8))
x1 = layers.LSTM(128, return_sequences=True)(input)
x2 = layers.LSTM(256, return_sequences=True)(x1)
x3 = layers.LSTM(10)(x2)
ouput = layers.Dense(10, activation='softmax')(x3)
model = models.Model(input, ouput)
model.summary()

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_20 (LSTM)               (None, 5, 128)            70144     
_________________________________________________________________
lstm_21 (LSTM)               (None, 5, 256)            394240    
_________________________________________________________________
lstm_22 (LSTM)               (None, 10)                10680     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
Total params: 475,174
Trainable params: 475,174
Non-trainable params: 0
_________________________________________________________________


# Many-to-many (same length)

In [ ]:
input = layers.Input(shape=(50, 8))
x = layers.LSTM(10, return_sequences=True)(input)
output = layers.Dense(20, activation='softmax')(x)
# output = layers.TimeDistributed(layers.Dense(20, activation='softmax'))(x)
model = models.Model(input, output)
model.summary()

Model: "functional_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 50, 8)]           0         
_________________________________________________________________
lstm_23 (LSTM)               (None, 50, 10)            760       
_________________________________________________________________
dense_4 (Dense)              (None, 50, 20)            220       
Total params: 980
Trainable params: 980
Non-trainable params: 0
_________________________________________________________________


## Many-to-many (different length) : Seq2seq

In [ ]:
input = layers.Input(shape=(50, 16))
x = layers.LSTM(1)(input)
model = models.Model(input, x)
model.summary()

Model: "functional_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 50, 16)]          0         
_________________________________________________________________
lstm_27 (LSTM)               (None, 1)                 72        
Total params: 72
Trainable params: 72
Non-trainable params: 0
_________________________________________________________________
